# Generated by Django 3.2.4 on 2021-07-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cutomer_shipingaddress_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipingaddress',
            old_name='addrees',
            new_name='address',
        ),
    ]
