# Generated by Django 3.2.4 on 2021-07-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_addrees_shipingaddress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipingaddress',
            old_name='address',
            new_name='addrees',
        ),
    ]
